version: "3.8"

services:
  order-services:
    container_name: order-services
    build: .
    environment:
      - ENV_PATH=/app/env/.env
    ports:
      - "8081:8081"
    networks:
      - order_network
    depends_on:
      - order-db

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=workshop_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - order_network

volumes:
  pgdata:

networks:
  order_network:
    driver: bridge
