version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: product_service_db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    ports:
      - 5438:5432
