version: "3.8"

services:
  product_db:
    image: postgres:16
    container_name: product_db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - product_network

  inventory_expirer:
    build: .
    container_name: inventory_expirer
    entrypoint: ["/app/worker"]
    environment:
      - ENV_PATH=/app/env/.env
    depends_on:
      - product_db
    networks:
      - product_network

  inventory_api:
    build: .
    container_name: inventory_api
    entrypoint: ["/app/inventory-api"]
    environment:
      - ENV_PATH=/app/env/.env
    ports:
      - 8083:8083
    depends_on:
      - product_db
    networks:
      - product_network

volumes:
  pgdata:

networks:
  product_network:
    driver: bridge
